version: "3"
services:
  donation-whistle:
    container_name: donation-whistle
    image: willthong/donation-whistle:latest
    volumes:
      - dw-db:/home/donation-whistle/db
    expose:
      - 5000
    environment:
      - DATABASE_URL=sqlite:////home/donation-whistle/db/donation-whistle.db
      - REDIS_URL=redis://redis:6379
      - LETSENCRYPT_HOST=
      - VIRTUAL_HOST=
      - VIRTUAL_PORT=5000
  dw-worker:
    container_name: dw-worker
    image: willthong/donation-whistle:latest
    entrypoint: poetry run rq worker donation-whistle-tasks
    environment:
      - DATABASE_URL=sqlite:////home/donation-whistle/db/donation-whistle.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - dw-db:/home/donation-whistle/db
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
  nginx-proxy:
    container_name: nginx-proxy
    build: ./nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - static:/home/app/weddingwrangle/static
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    ports:
      - 443:443
      - 80:80
    depends_on:
      - donation-whistle
  acme-companion:
    container_name: proxy-companion
    image: nginxproxy/acme-companion
    env_file:
      - .env.prod.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static:
  certs:
  html:
  vhost:
  acme:
  dw-db:
