version: "3"
services:
  donation-whistle:
    image: willthong/donation-whistle:latest
    volumes:
      - dw-db:/home/donation-whistle/db
    ports:
      - "80:5000"
    environment:
      - DATABASE_URL=sqlite:////home/donation-whistle/db/donation-whistle.db
      - REDIS_URL=redis://redis:6379
  worker:
    image: willthong/donation-whistle:latest
    entrypoint: poetry run rq worker donation-whistle-tasks
    environment:
      - DATABASE_URL=sqlite:////home/donation-whistle/db/donation-whistle.db
      - REDIS_URL=redis://redis:6379
    volumes:
      - dw-db:/home/donation-whistle/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
volumes:
  dw-db:
