"""Added donor alias notes

Revision ID: 349abbb65582
Revises: 4bd4376a1cd4
Create Date: 2023-08-28 14:28:22.100873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349abbb65582'
down_revision = '4bd4376a1cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_alias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_alias', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
