"""Initial donation data structure

Revision ID: 7aa0b3c182d3
Revises: 
Create Date: 2023-08-22 14:56:50.208738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa0b3c182d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_types_name'), ['name'], unique=False)

    op.create_table('donor_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('deregistered', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipient_name'), ['name'], unique=False)

    op.create_table('donor_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.Column('ec_donor_id', sa.Integer(), nullable=True),
    sa.Column('ec_regulated_entity_id', sa.Integer(), nullable=True),
    sa.Column('postcode', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['donor_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_alias_last_edited'), ['last_edited'], unique=False)
        batch_op.create_index(batch_op.f('ix_donor_alias_name'), ['name'], unique=False)

    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('ec_ref', sa.String(length=8), nullable=True),
    sa.Column('is_legacy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['donor'], ['donor_alias.id'], ),
    sa.ForeignKeyConstraint(['recipient'], ['recipient.id'], ),
    sa.ForeignKeyConstraint(['type'], ['donor_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_is_legacy'), ['is_legacy'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_value'), ['value'], unique=False)

    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['alias'], ['donor_alias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_name'))

    op.drop_table('donor')
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_value'))
        batch_op.drop_index(batch_op.f('ix_donation_is_legacy'))
        batch_op.drop_index(batch_op.f('ix_donation_date'))

    op.drop_table('donation')
    with op.batch_alter_table('donor_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_alias_name'))
        batch_op.drop_index(batch_op.f('ix_donor_alias_last_edited'))

    op.drop_table('donor_alias')
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipient_name'))

    op.drop_table('recipient')
    op.drop_table('donor_type')
    with op.batch_alter_table('donation_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_types_name'))

    op.drop_table('donation_types')
    # ### end Alembic commands ###
