"""Initial

Revision ID: a240e294a405
Revises: 
Create Date: 2023-08-31 12:22:41.372676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a240e294a405'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_type_name'), ['name'], unique=False)

    op.create_table('donor_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_edited', sa.DateTime(), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_alias_last_edited'), ['last_edited'], unique=False)
        batch_op.create_index(batch_op.f('ix_donor_alias_name'), ['name'], unique=False)

    op.create_table('donor_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('deregistered', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipient_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_alias_id', sa.Integer(), nullable=False),
    sa.Column('donor_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ec_donor_id', sa.Integer(), nullable=True),
    sa.Column('ec_regulated_entity_id', sa.Integer(), nullable=True),
    sa.Column('postcode', sa.String(length=7), nullable=True),
    sa.Column('company_registration_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donor_alias_id'], ['donor_alias.id'], ),
    sa.ForeignKeyConstraint(['donor_type_id'], ['donor_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donor_name'), ['name'], unique=False)

    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('donation_type_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('ec_ref', sa.String(length=8), nullable=True),
    sa.Column('is_legacy', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['donation_type_id'], ['donation_type.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_is_legacy'), ['is_legacy'], unique=False)
        batch_op.create_index(batch_op.f('ix_donation_value'), ['value'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_value'))
        batch_op.drop_index(batch_op.f('ix_donation_is_legacy'))
        batch_op.drop_index(batch_op.f('ix_donation_date'))

    op.drop_table('donation')
    with op.batch_alter_table('donor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_name'))

    op.drop_table('donor')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipient_name'))

    op.drop_table('recipient')
    op.drop_table('donor_type')
    with op.batch_alter_table('donor_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donor_alias_name'))
        batch_op.drop_index(batch_op.f('ix_donor_alias_last_edited'))

    op.drop_table('donor_alias')
    with op.batch_alter_table('donation_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_type_name'))

    op.drop_table('donation_type')
    # ### end Alembic commands ###
