"""Initial

Revision ID: d1e4cb018781
Revises: a240e294a405
Create Date: 2023-09-07 09:16:39.898998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e4cb018781'
down_revision = 'a240e294a405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donor_type', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
